  - name: Install Apache webserver
    yum:
       name: "{{ package }}"
       state: latest
    
  - name: Start Apache Service
    service:
        name: "{{ package }}"
        state: started

  - name: enable Apache Service
    service:
        name: "{{ package }}"
        enabled: yes

  - name: Check apache service
    command: service httpd status
    register: apache_status

  - debug: var=apache_status.stdout_lines

  - name: Disable the preset apache welcome page
    shell: "sed -i 's/^/#&/g' {{ welcome_page}}"

  - name: Copy your own html page
    template:
       src: index.html
       dest: /var/www/html
    notify: Restart Apache


