---

- hosts: all
  become: true
  gather_facts: true
 
  
  tasks:
  - name: Install packages
    yum:
      name: "{{ item }}"
      state: present
    with_items: 
       - git
       - vim
       - httpd
    when: ansible_os_family=="RedHat"
 
  - name: Install Packages1
    apt:
      name: "{{ item }}"
      state: present
    with_items:
       - git
       - vim
       - apache2
    when: ansible_os_family=="Debian"
